baseURL = 'http://mvasilenko.github.io/'
languageCode = 'en-us'
title = 'Michael Vasilenko blog'

[params]
  author = "Michael Vasilenko"
  description = "Personal blog."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/mvasilenko"
